In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [5]:
df.mean(numeric_only=True)

year                 1976.992812
life_expectancy_0      61.942232
dtype: float64

In [13]:
df[df["entity"].str.contains("Mexico", regex=True)]

       entity code  year  life_expectancy_0
12372  Mexico  MEX  1893            23.2900
12373  Mexico  MEX  1894            26.6200
12374  Mexico  MEX  1895            29.5200
12375  Mexico  MEX  1896            28.8000
12376  Mexico  MEX  1897            26.2400
...       ...  ...   ...                ...
12488  Mexico  MEX  2019            74.5302
12489  Mexico  MEX  2020            70.4492
12490  Mexico  MEX  2021            69.7499
12491  Mexico  MEX  2022            73.9731
12492  Mexico  MEX  2023            75.0690

[121 rows x 4 columns]

In [14]:
df.loc[df["code"].isnull()]

                                      entity code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [18]:
df.loc[df["code"].notnull(), ["entity", "year", "life_expectancy_0"]].head(3)

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [21]:
df.dropna(subset = ["code"], inplace = True)
df.isnull().sum()
df.shape

(20217, 4)

In [22]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [ ]:
resultado = ( 
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

In [27]:
mexico_1910 = df[(df["entity"] == "Mexico") & (df["year"] == 1910)]
mexico_1910.head(3)

       entity code  year  life_expectancy_0
12389  Mexico  MEX  1910               28.0